### ISSUE TITLE
Should it be possible to have a URN CRS specification? 

### ISSUE THREAD

**Issue by LaurensJN** [cityjson/cjio#166]
CJIO throws an error if any other CRS definition is used, including the OGC URN definition. See:

https://github.com/cityjson/cjio/blob/154d9f9ea8b27f54d5872ecb854ca21b6a329418/cjio/cityjson.py#L441

I was wondering why the `urn:ogc` definition is not supported? Some sample code to implement it:
```python
if "opengis.net/def/crs" in s or s.rfind("/") >= 0:
    return int(s[s.rfind("/")+1:])
elif "urn:ogc" in s.lower():
    return int(s[s.rfind(":")+1:])
raise ValueError(f"Invalid CRS string '{s}'. CRS needs to be formatted according to the OGC Name Type Specification: 'http://www.opengis.net/def/crs/{{authority}}/{{version}}/{{code}}' or ")
```

This is also specified in the CityJSON Community Standard 1.0: https://portal.ogc.org/files/95618#_crs

Related to: https://github.com/cityjson/cjio/issues/155

**Comment by balazsdukai** [comment]
cjio always uses the latest CityJSON specs, currently v1.1. There was a change in CityJSON v1.0 --> v1.1 in how the crs are defined. So what cjio expects is this https://www.cityjson.org/specs/1.1.3/#referencesystem-crs

What you see in the OGC community standard is secondary (and outdated). 
The information on https://www.cityjson.org/ is the reference for CityJSON.

**Comment by LaurensJN** [comment]
I cannot find the reasoning behind deprecating the URN definition, especially since the largest CityJSON dataset (3D BAG) is using this format. Why aren't both implemented?

**Comment by balazsdukai** [comment]
The reason for deprecating it in cjio is because cjio always works with the latest CityJSON version, which is v1.1. CityJSON v1.1 does not allow URNs, only URLs.
cjio is not backwards compatible with older CityJSON versions. It was never our intention and it is not in our plans to make it so either.
It is simple to upgrade a CityJSON file that uses an older schema to the latest CityJSON version. The command for that is `cjio upgrade`.
The current release of 3D BAG is using CityJSON v1.0, because v1.1 was not released yet at the time. In order to use the  3D BAG CityJSON files with cjio, they need to be upgraded first.

**Comment by hugoledoux** [comment]
the OGC moved to that new system, from URN, and we were suggested to do that too for CityJSON.

and I agree, URLs are better!

annoying that cjio doesn't support them, but cjio upgrade does it :)
